# This workflow will build and test the .NET solution in the src folder

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK (net10.0 preview)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Restore dependencies
        run: dotnet restore DreamBig.Faist.sln

      - name: Build
        run: dotnet build DreamBig.Faist.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test DreamBig.Faist.sln --configuration Release --no-build --verbosity normal
